apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - config/envoy.yaml
  name: envoy-config

resources:
- ingress.prod.yaml
- server-deployment.yaml
- server-service.yaml
